MIN_FACE_SIZE: 100  # Minimum size for a face detection in pixels, to trigger a session.
SESSION_TIMEOUT_SEC: 1  # Maximum time with no faces detected for the session to end.
SESSION_ACTIVATION_SEC: 2  # Minimum time in front of camera for the session to activate.
ROLLING_WINDOW_SIZE: 10000  # Maximum number of session data to store on disk before rolling deletion.