MIN_FACE_SIZE: 80  # Minimum size for a face detection in pixels, to trigger a session.
ROLLING_WINDOW_SIZE: 10000  # Maximum number of session data to store on disk before rolling deletion.
MAX_VECTOR_LENGTH: 10  # How many face detections to keep in one session (cyclic).
SESSION_LONG_LIFE_FRAMES: 150  # How many frames to keep a session open before (without detections) before ending it.
SESSION_SHORT_LIFE_FRAMES: 3  # How many frames to keep a session waiting for full activation (clustered MAX_VECTOR_LENGTH faces).